apiVersion: v1
kind: Pod
metadata:
  name: nginx-tute
  labels:
    apps: nginx

spec:
  containers:
  - name: nginx-load-balancer
    image: nginx:1.25.3
    command: ["/bin/sh", "-c"]
    args: ["echo 'hi how are you' >> /opt/test.txt  && sleep 120003"]
    ports:
    - containerPort: 80 
    volumeMounts: # inside the container which path will store attached files
    - name: test-volume
      mountPath: /opt 

  - name: nginx-reverse-proxy
    image: nginx:1.25.3
    ports:
      - containerPort: 80
    volumeMounts:
    - name: test-volume
      mountPath: /opt
  volumes:
  - name: test-volume
    emptyDir: {}  # is a temporay volume that is created when a Pod is assigned to a Node and exists as long as that Pod is running on that node.
                 # Used for short-lived storage
                 # emptyDir is the shared memory or share file among containers

