apiVersion: v1
kind: Pod
metadata:
  name: nginx-mysql-pod
  labels:
    app: nginx-mysql
spec:
  containers:
    - name: reverse-proxy
      image: nginx:1.25.3
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "250m" # Request 0.25 CPU Core
          memory: "128Mi" # Request 128 MB of Memory
        limits:
          cpu: "500m" 
          memory: "256Mi"
    - name: database
      image: mysql:8.0
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: my-secret-pw


# To add or remove new container must delete pod and create again

--- 
apiVersion: v1
kind: Pod
metadata:
  name: nginx-loadbalancer
  labels:
    app: nginx-mysql
spec:
  containers:
    - name: load-balancer
      image: nginx:1.25.3
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "250m"
          memory: "128Mi" 
        limits:
          cpu: "500m" 
          memory: "256Mi"