apiVersion: v1
kind: Pod
metadata:
  name: nginx-mysql-pod
  labels:
    app: nginx-mysql
spec:
  containers:
    - name: reverse-proxy
      image: nginx:1.25.3
      ports:
        - containerPort: 80
    
    - name: database
      image: mysql:8.0
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: my-secret-pw


# To add or remove new container must delete pod and create again