apiVersion: v1
kind: Pod
metadata:
  name: inmemory-database
  labels:
    app: redis
spec:
  containers:
  - name: redis-inmemory
    image: redis/redis-stack:latest
    ports:
      - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  type: NodePort
  ports:
    - port: 6379 # Pod Port
      targetPort: 6379 # Container Port 
      nodePort: 30007 # Port on host i can access